export type { Info, Capabilities, Tag, Source } from "./capability"
export { Tag, Source, Capabilities } from "./capability"
export { resolveToolTags, registerToolTags } from "./tags"
export { resolve } from "./resolver"
export * as CapabilityRegistry from "./registry"
export { fromNativeTool } from "./adapters/native"
export { fromPluginTool } from "./adapters/plugin"
export { fromMcpTool } from "./adapters/mcp"
